### ISSUE TITLE
IndexData not working for hours and minutes

### ISSUE THREAD

**Issue by ubanning** [MarketDataApp/documentation#24]
Hello, thanks for the project.
Using a basic example provided:
```INDEXDATA("SPX", "close", "9/23/2022", "10/23/2022", "hourly")```
It is returning `NO DATA`, if you change it to `"minutely"` the same problem occurs.

Thanks.

**Comment by MarketDataApp** [comment]
Hi, this repo is for issues with the documentation only. Please open a helpdesk ticket in your customer dashboard if you have any issues with the service or data.

**Comment by MarketDataApp** [comment]
Closed.
